# Basic information about this project
[content]
name = "SwitchableCloak"
description = ""
version = "1.6.3"
authors = ["Priler"]
game_version = "4.04"
scripts_root = "scripts"

# Any dependencies that this project might need
[dependencies]
content0 = true

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-system/#manifest-format
